In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Oneformer + driving + semantic VS + complexity-infused

In [20]:
test_no_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_test_semantic_driving_oneformer_32_continuous.csv')
pred_no_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_pred_semantic_driving_oneformer_32_continuous.csv')
test_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_test_complexity_semantic_driving_oneformer_32_continuous.csv')
pred_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_pred_complexity_semantic_driving_oneformer_32_continuous.csv')

In [21]:
def return_confusion_matrix(test_no_complexity_data, pred_no_complexity_data, test_complexity_data, pred_complexity_data):
    no_complexity_data = pd.concat([test_no_complexity_data, pred_no_complexity_data], axis=1)
    complexity_data = pd.concat([test_complexity_data, pred_complexity_data], axis=1)
    no_complexity_data['pred'] = no_complexity_data['crash_likelihood'] == no_complexity_data['crash_pred']
    complexity_data['pred'] = complexity_data['crash_likelihood'] == complexity_data['crash_pred']
    final_data = pd.concat([no_complexity_data['pred'], complexity_data['pred']], axis=1)
    final_data.columns = ['pred1', 'pred2']
    # create a confusion matrix
    confusion_matrix = np.zeros((2, 2))
    confusion_matrix[0, 0] = final_data[(final_data['pred1'] == True) & (final_data['pred2'] == True)].shape[0]
    confusion_matrix[0, 1] = final_data[(final_data['pred1'] == True) & (final_data['pred2'] == False)].shape[0]
    confusion_matrix[1, 0] = final_data[(final_data['pred1'] == False) & (final_data['pred2'] == True)].shape[0]
    confusion_matrix[1, 1] = final_data[(final_data['pred1'] == False) & (final_data['pred2'] == False)].shape[0]

    return confusion_matrix

In [22]:
# create a confusion matrix
con = return_confusion_matrix(test_no_complexity_data, pred_no_complexity_data, test_complexity_data, pred_complexity_data)
con

array([[2169.,   61.],
       [ 135.,  182.]])

In [23]:
from scipy import stats
statistics = (abs(con[0, 1] - con[1, 0]) - 1)**2 / (con[0, 1] + con[1, 0])
# compare it with chi-square distribution with df = 1
print(statistics)
# calculate p-value
p_value = 1 - stats.chi2.cdf(statistics, 1)
print(p_value)
# p-value is 0.05
# if statistics > 3.841, then reject the null hypothesis
# if statistics < 3.841, then accept the null hypothesis

27.18877551020408
1.8452687156056413e-07


### Oneformer + driving VS + complexity-infused

In [24]:
test_no_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_test_driving_oneformer_32_continuous.csv')
pred_no_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_pred_driving_oneformer_32_continuous.csv')
test_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_test_oneformer_driving_complexity_oneformer_32_continuous.csv')
pred_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_pred_oneformer_driving_complexity_oneformer_32_continuous.csv')
con = return_confusion_matrix(test_no_complexity_data, pred_no_complexity_data, test_complexity_data, pred_complexity_data)
con

array([[1850.,  281.],
       [ 131.,  285.]])

In [25]:
statistics = (abs(con[0, 1] - con[1, 0]) - 1)**2 / (con[0, 1] + con[1, 0])
# compare it with chi-square distribution with df = 1
print(statistics)
# calculate p-value
p_value = 1 - stats.chi2.cdf(statistics, 1)
print(p_value)

53.88592233009709
2.1249668691325496e-13


### Oneformer VS + complexity-infused

In [26]:
test_no_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_test_oneformer_32_continuous.csv')
pred_no_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_pred_oneformer_32_continuous.csv')
test_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_test_complexity_oneformer_32_continuous.csv')
pred_complexity_data = pd.read_csv('../../0_data/2_results_pred/y_pred_complexity_oneformer_32_continuous.csv')
con = return_confusion_matrix(test_no_complexity_data, pred_no_complexity_data, test_complexity_data, pred_complexity_data)
con

array([[1715.,  154.],
       [ 266.,  412.]])

In [27]:
statistics = (abs(con[0, 1] - con[1, 0]) - 1)**2 / (con[0, 1] + con[1, 0])
# compare it with chi-square distribution with df = 1
print(statistics)
# calculate p-value
p_value = 1 - stats.chi2.cdf(statistics, 1)
print(p_value)

29.335714285714285
6.086355153200884e-08
